services:
  backend:
    build: .
    container_name: voice_eda_backend
    ports:
      - '8000:8000'
    volumes:
      - .:/app # Mount the application code
      - db_data:/app/database # Use a named volume for the database
    env_file:
      - .env
    environment:
      - GROQ_API_KEY=${GROQ_API_KEY}
      - GROQ_API_KEY1=${GROQ_API_KEY1}
      - GROQ_API_KEY2=${GROQ_API_KEY2}
      - GROQ_API_KEY3=${GROQ_API_KEY3}
      - GROQ_API_KEY4=${GROQ_API_KEY4}

volumes:
  db_data: # Define the named volume
